/*
  Warnings:

  - You are about to drop the `TELEPHONE` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `USER` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "TELEPHONE" DROP CONSTRAINT "TELEPHONE_FK_ID_USER_fkey";

-- DropForeignKey
ALTER TABLE "USER" DROP CONSTRAINT "USER_FK_ID_TYPE_USER_fkey";

-- DropTable
DROP TABLE "TELEPHONE";

-- DropTable
DROP TABLE "USER";

-- CreateTable
CREATE TABLE "USERS" (
    "ID_USER" SERIAL NOT NULL,
    "DS_USERNAME" TEXT NOT NULL,
    "DS_PASSWORD" TEXT NOT NULL,
    "DS_EMAIL" TEXT NOT NULL,
    "DS_USER_NAME" TEXT NOT NULL,
    "DS_USER_LASTNAME" TEXT NOT NULL,
    "NR_CPF" TEXT NOT NULL,
    "FK_ID_TYPE_USER" INTEGER NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID_USER")
);

-- CreateTable
CREATE TABLE "TELEPHONES" (
    "ID_TELEPHONE" SERIAL NOT NULL,
    "NR_TELEPHONE" TEXT NOT NULL,
    "DS_TELEPHONE" TEXT NOT NULL,
    "FK_ID_USER" INTEGER NOT NULL,

    CONSTRAINT "TELEPHONES_pkey" PRIMARY KEY ("ID_TELEPHONE")
);

-- CreateTable
CREATE TABLE "EMPLOYEES" (
    "ID_EMPLOYEES" SERIAL NOT NULL,
    "FK_ID_USER" INTEGER NOT NULL,
    "FK_ID_ESTABLISHMENT" INTEGER NOT NULL,

    CONSTRAINT "EMPLOYEES_pkey" PRIMARY KEY ("ID_EMPLOYEES")
);

-- CreateTable
CREATE TABLE "ESTABLISHMENTS" (
    "ID_ESTABLISHMENT" SERIAL NOT NULL,
    "DS_CORPORATE_NAME" TEXT NOT NULL,
    "DS_REPRESENTATIVE_NAME" TEXT NOT NULL,
    "NR_CNPJ" TEXT NOT NULL,
    "DS_EMAIL" TEXT NOT NULL,
    "ESTABLISHMENT_LOGO" BYTEA NOT NULL,

    CONSTRAINT "ESTABLISHMENTS_pkey" PRIMARY KEY ("ID_ESTABLISHMENT")
);

-- CreateTable
CREATE TABLE "ESTABLISHMENT_PAYMENTES" (
    "ID_ESTABLISHMENT_PAYMENTE" SERIAL NOT NULL,
    "FK_ID_TYPE_PAYMENT" INTEGER NOT NULL,
    "FK_ID_ESTABLISHMENT" INTEGER NOT NULL,

    CONSTRAINT "ESTABLISHMENT_PAYMENTES_pkey" PRIMARY KEY ("ID_ESTABLISHMENT_PAYMENTE")
);

-- CreateTable
CREATE TABLE "TYPE_PAYMENT" (
    "ID_TYPE_PAYMENT" SERIAL NOT NULL,
    "DS_TYPE_PAYMENT" TEXT NOT NULL,

    CONSTRAINT "TYPE_PAYMENT_pkey" PRIMARY KEY ("ID_TYPE_PAYMENT")
);

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_FK_ID_TYPE_USER_fkey" FOREIGN KEY ("FK_ID_TYPE_USER") REFERENCES "TYPE_USER"("ID_TYPE_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TELEPHONES" ADD CONSTRAINT "TELEPHONES_FK_ID_USER_fkey" FOREIGN KEY ("FK_ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_FK_ID_USER_fkey" FOREIGN KEY ("FK_ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_FK_ID_ESTABLISHMENT_fkey" FOREIGN KEY ("FK_ID_ESTABLISHMENT") REFERENCES "ESTABLISHMENTS"("ID_ESTABLISHMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTES" ADD CONSTRAINT "ESTABLISHMENT_PAYMENTES_FK_ID_TYPE_PAYMENT_fkey" FOREIGN KEY ("FK_ID_TYPE_PAYMENT") REFERENCES "TYPE_PAYMENT"("ID_TYPE_PAYMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTES" ADD CONSTRAINT "ESTABLISHMENT_PAYMENTES_FK_ID_ESTABLISHMENT_fkey" FOREIGN KEY ("FK_ID_ESTABLISHMENT") REFERENCES "ESTABLISHMENTS"("ID_ESTABLISHMENT") ON DELETE RESTRICT ON UPDATE CASCADE;
