FROM node:18.14.2-alpine3.17

WORKDIR /app

COPY --chown=node:node ./package*.json ./

RUN npm install

COPY --chown=node:node ./ ./

RUN npm run prisma:db:push

RUN npm run prisma:generate

RUN npm run build

CMD ["npm","run", "start"]
