version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app-node:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    entrypoint: dockerize -wait tcp://db-app:${POSTGRES_PORT} -timeout 300s -wait-retry-interval 30s docker-entrypoint.sh
    command: npm run start:dev
    tty: true
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app-network
    volumes:
      - .:/app
    depends_on:
      - db-app
  db-app:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
