/*
  Warnings:

  - You are about to drop the `ESTABLISHMENT_PAYMENTES` table. If the table is not empty, all the data it contains will be lost.
  - A unique constraint covering the columns `[NR_CPF]` on the table `USERS` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `UPDATE_AT` to the `USERS` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTES" DROP CONSTRAINT "ESTABLISHMENT_PAYMENTES_FK_ID_ESTABLISHMENT_fkey";

-- DropForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTES" DROP CONSTRAINT "ESTABLISHMENT_PAYMENTES_FK_ID_TYPE_PAYMENT_fkey";

-- AlterTable
ALTER TABLE "USERS" ADD COLUMN     "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "UPDATE_AT" TIMESTAMP(3) NOT NULL;

-- DropTable
DROP TABLE "ESTABLISHMENT_PAYMENTES";

-- CreateTable
CREATE TABLE "ESTABLISHMENT_PAYMENTS" (
    "ID_ESTABLISHMENT_PAYMENTE" SERIAL NOT NULL,
    "FK_ID_TYPE_PAYMENT" INTEGER NOT NULL,
    "FK_ID_ESTABLISHMENT" INTEGER NOT NULL,

    CONSTRAINT "ESTABLISHMENT_PAYMENTS_pkey" PRIMARY KEY ("ID_ESTABLISHMENT_PAYMENTE")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_NR_CPF_key" ON "USERS"("NR_CPF");

-- AddForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTS" ADD CONSTRAINT "ESTABLISHMENT_PAYMENTS_FK_ID_TYPE_PAYMENT_fkey" FOREIGN KEY ("FK_ID_TYPE_PAYMENT") REFERENCES "TYPE_PAYMENT"("ID_TYPE_PAYMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ESTABLISHMENT_PAYMENTS" ADD CONSTRAINT "ESTABLISHMENT_PAYMENTS_FK_ID_ESTABLISHMENT_fkey" FOREIGN KEY ("FK_ID_ESTABLISHMENT") REFERENCES "ESTABLISHMENTS"("ID_ESTABLISHMENT") ON DELETE RESTRICT ON UPDATE CASCADE;
