-- CreateTable
CREATE TABLE "USER" (
    "ID_USER" SERIAL NOT NULL,
    "DS_USERNAME" TEXT NOT NULL,
    "DS_PASSWORD" TEXT NOT NULL,
    "DS_EMAIL" TEXT NOT NULL,
    "DS_USER_NAME" TEXT NOT NULL,
    "DS_USER_LASTNAME" TEXT NOT NULL,
    "NR_CPF" TEXT NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID_USER")
);
