-- CreateTable
CREATE TABLE "TYPE_SERVICE" (
    "ID_TYPE_SERVICE" SERIAL NOT NULL,
    "DS_TYPE_SERVICE" TEXT NOT NULL,

    CONSTRAINT "TYPE_SERVICE_pkey" PRIMARY KEY ("ID_TYPE_SERVICE")
);

-- CreateTable
CREATE TABLE "SERVICES" (
    "ID_SERVICE" SERIAL NOT NULL,
    "DS_SERVICE" TEXT NOT NULL,
    "NR_VALOR" DOUBLE PRECISION NOT NULL,
    "TIME_DURATION" TIMESTAMP(3) NOT NULL,
    "FK_ID_ESTABLISHMENT" INTEGER NOT NULL,
    "FK_ID_TYPE_SERVICE" INTEGER NOT NULL,

    CONSTRAINT "SERVICES_pkey" PRIMARY KEY ("ID_SERVICE")
);

-- CreateTable
CREATE TABLE "SCHEDULES" (
    "ID_SCHEDULES" SERIAL NOT NULL,
    "DT_SCHEDULE_INITIAL" TIMESTAMP(3) NOT NULL,
    "DT_SCHEDULE_END" TIMESTAMP(3) NOT NULL,
    "FK_ID_SERVICE" INTEGER NOT NULL,
    "FK_ID_USER" INTEGER NOT NULL,
    "FK_ID_TYPE_PAYMENT" INTEGER NOT NULL,

    CONSTRAINT "SCHEDULES_pkey" PRIMARY KEY ("ID_SCHEDULES")
);

-- AddForeignKey
ALTER TABLE "SERVICES" ADD CONSTRAINT "SERVICES_FK_ID_ESTABLISHMENT_fkey" FOREIGN KEY ("FK_ID_ESTABLISHMENT") REFERENCES "ESTABLISHMENTS"("ID_ESTABLISHMENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SERVICES" ADD CONSTRAINT "SERVICES_FK_ID_TYPE_SERVICE_fkey" FOREIGN KEY ("FK_ID_TYPE_SERVICE") REFERENCES "TYPE_SERVICE"("ID_TYPE_SERVICE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULES" ADD CONSTRAINT "SCHEDULES_FK_ID_SERVICE_fkey" FOREIGN KEY ("FK_ID_SERVICE") REFERENCES "SERVICES"("ID_SERVICE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULES" ADD CONSTRAINT "SCHEDULES_FK_ID_USER_fkey" FOREIGN KEY ("FK_ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULES" ADD CONSTRAINT "SCHEDULES_FK_ID_TYPE_PAYMENT_fkey" FOREIGN KEY ("FK_ID_TYPE_PAYMENT") REFERENCES "TYPE_PAYMENT"("ID_TYPE_PAYMENT") ON DELETE RESTRICT ON UPDATE CASCADE;
