# name: cd-api-dev

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: sa-east-1

#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18.14.2

#       - name: Install dependencies
#         run: npm install

#       - name: Test application
#         run: npm run test

#       - name: Install SSH client
#         run: sudo apt-get install -y openssh-client

#       - name: Deploy application
#         run: |
#           export PRIVATE_KEY="${{ secrets.AWS_EC2_SSH_DEV  }}"
#           export INSTANCE_HOST="54.207.235.172"

#           # Configurar a chave privada para autenticação SSH
#           mkdir -p ~/.ssh
#           echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan -H "$INSTANCE_HOST" >> ~/.ssh/known_hosts

#           # Conectar à instância EC2 e executar o comando de reinicialização do Docker Compose
#           ssh -i ~/.ssh/id_rsa  ubuntu@$INSTANCE_HOST  "cd ~/app && git pull && sudo docker compose -f docker-compose.prod.yml up -d --build"

name: Continuos Delivery Deploy to EC2 (Dev)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          export PRIVATE_KEY="${{ secrets.AWS_EC2_SSH_DEV  }}"
          export INSTANCE_HOST="54.207.235.172"
          ssh-keyscan INSTANCE_HOST >> ~/.ssh/known_hosts
          ssh -i PRIVATE_KEY ubuntu@INSTANCE_HOST 'cd /home/ubuntu/app && git pull && npm install && npm run build'

      - name: Restart application
        run: |
          export PRIVATE_KEY="${{ secrets.AWS_EC2_SSH_DEV  }}"
          export INSTANCE_HOST="54.207.235.172"
          ssh -i PRIVATE_KEY ubuntu@INSTANCE_HOST 'pm2 restart app'
