name: Continuos Delivery Deploy to EC2 (Dev)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Install PM2
        run: npm install -g pm2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Test application
        run: npm run test

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Update files in EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '54.207.235.172'
          username: 'ubuntu'
          key: ${{ secrets.AWS_EC2_SSH_DEV }}
          script: |
            cd /home/ubuntu/app
            git pull

      - name: Update Database
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '54.207.235.172'
          username: 'ubuntu'
          key: ${{ secrets.AWS_EC2_SSH_DEV }}
          script: |
            cd /home/ubuntu/app
            npm run prisma:db:push

      - name: Transfer files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: '54.207.235.172'
          username: 'ubuntu'
          key: ${{ secrets.AWS_EC2_SSH_DEV }}
          source: dist/
          target: /home/ubuntu/app

      - name: SSH into EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '54.207.235.172'
          username: 'ubuntu'
          key: ${{ secrets.AWS_EC2_SSH_DEV }}
          script: |
            cd /home/ubuntu/app
            pm2 restart app
